

daily_charger_station_path : './data/加油站充电销售日报2024.4.1-4.10.xls'
daily_charger_path : './data/电桩充电统计2024.4.1-4.10.xls'
excel_output_path : './output/厦门充电业务经营周报20240401-20240410.xlsx'
days_span : 7
recharge_station:
  福建-厦门-同安-梧侣充电站: [ 28, 6 ]
  福建-厦门-思明-文屏充电站: [ 46, 20 ]
  福建-厦门-思明-石油大厦停车场充电站: [ 0, 8 ]
  福建-厦门-湖里-前埔北充电站: [ 20, 0 ]
  福建-厦门-湖里-高殿充电站: [ 10, 0 ]
  福建-厦门-翔安-新曙路充电站: [ 12, 0 ]

need_QoQ: true
QoQ_file: './output/厦门充电业务经营周报20240301-20240310.xlsx'
specify_cols_order:
  - 站点
  - 充电量KW.h
  - 电费
  - 服务费
  - 实收金额
  - 在用抢数
  - 快充枪数
  - 慢充枪数
  - 充电量(万度)
  - 电费(万元)
  - 服务费(万元)
  - 实收金额(万元)
  - 度电服务费(元)
  - 度电营业额(元)
  - 慢充电量（度）
  - 快充电量（度）
  - 单枪日均充电度数
  - 单枪日均快充度数
  - 单枪日均慢充度数
  - 充电量环比
  - 上周期充电量KW.h

need_draw_chart: true
chart_config:
  bar_width : 0.3  # 调整此数值来更改柱状图的宽度，默认为0.8
  line_label_x_offset : 0.35  # 调整偏移量，使其与柱状图脱离重叠
  line_label_y_offset : -2  # 设置 y 轴方向的偏移量
  fontsize : 18
  subtitle : 充电站电费及环比变化
  bar_label: 充电量
  y1label: 充电量(万度)
  line_lable: 充电量环比
  y2label: 充电量环比(%)
  export_name: '20240301-20240310.jpg'